name: integration_tests

on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: ['mbzirc_sim']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install and run xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :1 -ac -noreset -core -screen 0 1280x1024x24 &
      - name: Run build script
        id: build_docker
        run: |
            bash -xe ./docker/build.bash ${{ matrix.image_name }}
            echo "::set-output name=name::${{ matrix.image_name }}:latest"
      - name: Run tests
        run: |
          docker run -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix \
              ${{ steps.build_docker.outputs.name }} \
              /bin/bash -c \
                'source /home/$USERNAME/mbzirc_ws/install/setup.bash && \
                 cd /home/$USERNAME/mbzirc_ws && \
                 colcon test --merge-install \
                             --event-handlers console_direct+ \
                             --packages-select mbzirc_ros && \
                 colcon test-result'
